# Generated by Django 5.1.6 on 2025-04-23 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hall_options_alter_theater_options_and_more'),
        ('perfomance', '0004_alter_performance_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Cпектакли'},
        ),
        migrations.AlterModelOptions(
            name='performancecategory',
            options={'verbose_name': 'Категория спектакля', 'verbose_name_plural': 'Категории спектаклей'},
        ),
        migrations.AlterModelOptions(
            name='performanceschedule',
            options={'verbose_name': 'Расписание спектаклей', 'verbose_name_plural': 'Расписание спектаклей'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='perfomance.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='perfomance.performancecategory', verbose_name='категория спетакля'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='description',
            field=models.TextField(verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='duration_time',
            field=models.DurationField(verbose_name='Время продолжительности'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='main.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='main.theater', verbose_name='Театр'),
        ),
        migrations.AlterField(
            model_name='performancecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='performancecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='available_seats',
            field=models.IntegerField(verbose_name='Колличество мест'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='perfomance.performance', verbose_name='Спектакль '),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.FloatField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='performances',
            field=models.ManyToManyField(related_name='promotions', to='perfomance.performance', verbose_name='Спекталь'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата старта акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='perfomance.performance', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
