# Generated by Django 5.1.6 on 2025-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0005_alter_like_options_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='hall',
        ),
    ]
