# Generated by Django 5.1.6 on 2025-04-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hall'),
        ('perfomance', '0006_remove_performance_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='main.hall', verbose_name='Зал'),
        ),
    ]
