# Generated by Django 5.1.6 on 2025-04-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hall'),
        ('perfomance', '0007_performance_hall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='perfomance.performancecategory', verbose_name='Категория спектакля'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(limit_choices_to={'theater': models.F('theater')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='main.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='available_seats',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='performanceschedule',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='perfomance.performance', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='performances',
            field=models.ManyToManyField(related_name='promotions', to='perfomance.performance', verbose_name='Спектакль'),
        ),
    ]
