# Generated by Django 5.1.6 on 2025-04-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hall'),
        ('perfomance', '0009_performanceschedule_hall_performanceschedule_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='theater',
        ),
        migrations.AlterField(
            model_name='performance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='main.hall', verbose_name='Зал'),
        ),
    ]
