# Generated by Django 5.1.6 on 2025-04-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0010_remove_performance_theater_alter_performance_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='hall',
        ),
    ]
