# Generated by Django 5.1.6 on 2025-05-22 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0012_performance_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Заглушка',
                'verbose_name_plural': 'Заглушки',
            },
        ),
        migrations.CreateModel(
            name='PlaceholderThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfomance.placeholderrelation', verbose_name='Заглушка')),
                ('related_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfomance.performance', verbose_name='Связанный объект')),
            ],
            options={
                'verbose_name': 'Связь заглушки',
                'verbose_name_plural': 'Связи заглушек',
            },
        ),
    ]
