# Generated by Django 5.1.6 on 2025-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0013_placeholderrelation_placeholderthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='performance_files/', verbose_name='Файл'),
        ),
    ]
