# Generated by Django 5.1.6 on 2025-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0014_performance_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='related_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на дополнительную информацию'),
        ),
    ]
