# Generated by Django 5.1.6 on 2025-06-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0015_performance_related_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholderrelation',
            name='related_performances',
            field=models.ManyToManyField(related_name='placeholder_relations', through='perfomance.PlaceholderThrough', to='perfomance.performance', verbose_name='Связанные спектакли (через заглушку)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
