# Generated by Django 5.1.6 on 2025-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0017_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена билета'),
        ),
    ]
