# Generated by Django 5.1.6 on 2025-06-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0018_performanceschedule_price'),
        ('users', '0010_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='products',
            field=models.ManyToManyField(related_name='performances', to='users.product', verbose_name='Товары'),
        ),
    ]
