# Generated by Django 5.1.6 on 2025-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0019_performance_products'),
        ('users', '0010_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='products',
        ),
        migrations.AddField(
            model_name='performanceschedule',
            name='products',
            field=models.ManyToManyField(related_name='schedules', to='users.product', verbose_name='Товары'),
        ),
    ]
