# Generated by Django 5.1.6 on 2025-06-16 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0020_remove_performance_products_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceschedule',
            name='products',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('completed', 'Выполнен')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email заказчика')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон заказчика')),
                ('payment_method', models.CharField(default='Онлайн', max_length=50, verbose_name='Метод оплаты')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество билетов')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за билет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='perfomance.order', verbose_name='Заказ')),
                ('performance_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfomance.performanceschedule', verbose_name='Расписание спектакля')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
