# Generated by Django 5.1.6 on 2025-06-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0022_order_delivery_address_and_more'),
    ]

    operations = [
    ]
