# Generated by Django 5.1.6 on 2025-06-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_product_options_alter_cart_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на складе'),
        ),
    ]
