# Generated by Django 5.1.6 on 2025-06-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0018_performanceschedule_price'),
        ('users', '0006_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='performance_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='perfomance.performanceschedule', verbose_name='Расписание спектакля'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('sold_out', 'Отсутствует')], default='available', max_length=20, verbose_name='Статус товара'),
        ),
    ]
