# Generated by Django 5.1.6 on 2025-06-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_qty_to_product'),
        ('users', '0008_remove_product_performance_schedule_and_more'),
    ]

    operations = [
    ]
