# Generated by Django 5.1.6 on 2025-06-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance', '0021_remove_performanceschedule_products_order_orderitem'),
        ('users', '0010_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
