# Generated by Django 5.1.6 on 2025-04-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_theater_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name'], 'verbose_name': 'Театр', 'verbose_name_plural': 'Театры'},
        ),
        migrations.AlterField(
            model_name='hall',
            name='number_hall',
            field=models.IntegerField(verbose_name='Номер зала'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='main.theater', verbose_name='Театр'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='address',
            field=models.TextField(verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='description',
            field=models.TextField(verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название театра'),
        ),
    ]
