# Generated by Django 5.1.6 on 2025-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hall_options_alter_theater_options_and_more'),
        ('perfomance', '0006_remove_performance_hall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
