# Generated by Django 5.1.6 on 2025-04-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hall', models.IntegerField(verbose_name='Номер зала')),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='main.theater', verbose_name='Театр')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
